<?xml version="1.0" ?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="details"> 
  <xacro:macro name="details" params="parent body_height body_width body_large">
 <!--gazebo reference="body_to_tail">
      <provideFeedback>true</provideFeedback>
      <disableFixedJointLumping>true</disableFixedJointLumping>
    </gazebo-->
   <!--gazebo reference="neck_to_head">
      <provideFeedback>true</provideFeedback>
      <disableFixedJointLumping>true</disableFixedJointLumping>
    </gazebo-->
    <!--gazebo reference="body_to_neck">
      <provideFeedback>true</provideFeedback>
      <disableFixedJointLumping>true</disableFixedJointLumping>
    </gazebo-->

 <link name="neck">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.01"/>
      <xacro:cuboid_inertia_def x="${body_large/7}" y="${body_width/7}" z="${body_height/7}" mass="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <box size="${body_large/7} ${body_width/7} ${body_height/7}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <box size="${body_large/7} ${body_width/7} ${body_height/7}" />
      </geometry>
    </collision>
  </link>
    <link name="head">
    <inertial>
      <origin xyz="${body_large/4} 0 0" />
      <mass value="1.5"/>
      <xacro:cuboid_inertia_def x="${body_large/2}" y="${body_width*0.8}" z="${body_height*0.6}" mass="1.5"/>
    </inertial>
    <visual>
      <origin xyz="${body_large*0.5/2} 0 0" rpy="0 0 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <box size="${body_large*0.5} ${body_width*0.8} ${body_height*0.6}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${body_large*0.5/2} 0 0" rpy="0 0 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <box size="${body_large*0.5} ${body_width*0.8} ${body_height*0.6}" />
      </geometry>
    </collision>
  </link>
  <link name="tail">
    <inertial>
      <origin xyz="-0.200 0 0" />
      <mass value="0.5"/>
      <xacro:cuboid_inertia_def x="${body_large*2}" y="${body_width}" z="${body_height/2}" mass="0.5"/>
    </inertial>
    <visual>
      <origin xyz="-0.250 0 0" rpy="0 ${-M_PI/2} 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <mesh filename="package://simple_biped/cone.stl" scale="0.005 0.005 0.005"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.250 0 0" rpy="0 ${-M_PI/2} 0" />
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <geometry>
        <mesh filename="package://simple_biped/cone.stl" scale="0.005 0.005 0.005"/>
      </geometry>
    </collision>
  </link>
  <joint name="body_to_tail" type="fixed">
    <parent link="${parent}"/>
    <child link="tail"/>
    <origin xyz="${-body_large/2} 0 0" rpy="0 0 0" />
  </joint>
 <joint name="body_to_neck" type="fixed">
    <parent link="${parent}"/>
    <child link="neck"/>
    <origin xyz="${body_large/2} 0 ${body_height/3}" rpy="0 0 0" />
  </joint>
  <joint name="neck_to_head" type="fixed">
    <parent link="neck"/>
    <child link="head"/>
    <origin xyz="${body_large/14} 0 0" rpy="0 0 0" />
  </joint>
</xacro:macro>
</robot>