<?xml version="1.0" ?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="leg">

 <!--xacro:property name="body_height" value="0.106" /-->
 <!--xacro:property name="body_width" value="0.109" /-->
 <!--xacro:property name="body_large" value="0.102" /-->
 <xacro:property name="M_PI" value="3.1415926535897931" />
<xacro:property name="pelvis_height" value="0.028652" />
 <xacro:property name="pelvis_width" value="0.08175" />
 <xacro:property name="pelvis_large" value="0.045" />
 <xacro:property name="thigh_virtual_height" value="0.001" />
 <xacro:property name="thigh_virtual_width" value="0.001" />
 <xacro:property name="thigh_virtual_large" value="0.001" />
<xacro:property name="thigh_height" value="0.125" />
 <xacro:property name="thigh_width" value="0.035" />
 <xacro:property name="thigh_large" value="0.045" />
 <xacro:property name="tibia_height" value="0.130" />
 <xacro:property name="tibia_width" value="0.035" />
 <xacro:property name="tibia_large" value="0.045" />
  <xacro:property name="ankle_height" value="0.0745" />
 <xacro:property name="ankle_width" value="0.035" />
 <xacro:property name="ankle_large" value="0.045" />
   <xacro:property name="phalange_height" value="0.0745" />
 <xacro:property name="phalange_width" value="0.035" />
 <xacro:property name="phalange_large" value="0.045" />
  <xacro:macro name="leg" params="side parent reflect body_height body_width body_large">

      <!-- Transmissions -->
    <xacro:joint_transmission joint="${side}_pelvis_joint"/>    
    <xacro:joint_transmission joint="${side}_thigh_yaw_joint"/>
    <xacro:joint_transmission joint="${side}_thigh_pitch_joint"/>
    <xacro:joint_transmission joint="${side}_tibia_joint"/>
    <xacro:joint_transmission joint="${side}_ankle_joint"/>
    <xacro:joint_transmission joint="${side}_phalange_joint"/>
  <link name="${side}_pelvis" >
    <inertial>
      <origin xyz="0.000000 0.000480 0.018437" />
      <mass value="0.167"/>
      <inertia ixx="0.12259691"  ixy="0.00071127469"  ixz="0.00081143913" iyx="0.00071127469" iyy="0.11066637" iyz="-0.0071635476" izx="0.00081143913" izy="-0.0071635476" izz="0.041877668" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*pelvis_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${pelvis_large} ${pelvis_width} ${pelvis_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*pelvis_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${pelvis_large} ${pelvis_width} ${pelvis_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_thigh_yaw" >
    <inertial>
      <origin xyz="0.000079 0.018242 0.013873" />
      <mass value="0.11904336"/>
      <inertia ixx="0.097950272"  ixy="0.0012119368"  ixz="-0.00021223016" iyx="0.00122119368" iyy="0.032848287" iyz="-0.0019474021" izx="-0.00021223016" izy="-0.0019474021" izz="0.11493509" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_virtual_large} ${thigh_virtual_width} ${thigh_virtual_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${thigh_virtual_large} ${thigh_virtual_width} ${thigh_virtual_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_thigh" >
    <inertial>
      <origin xyz="-0.062965 -0.000323 0.000692" />
      <mass value="0.11904336"/>
      <inertia ixx="0.097950272"  ixy="0.0012119368"  ixz="-0.00021223016" iyx="0.00122119368" iyy="0.032848287" iyz="-0.0019474021" izx="-0.00021223016" izy="-0.0019474021" izz="0.11493509" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*thigh_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_large} ${thigh_width} ${thigh_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*thigh_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_large} ${thigh_width} ${thigh_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_tibia" >
    <inertial>
      <origin xyz="-0.053955 0.006548 -0.000592" />
      <mass value="0.070309794"/>
      <inertia ixx="0.093369608"  ixy="-0.00093567395"  ixz="-0.00023992085" iyx="-0.00093567395" iyy="0.046295534" iyz="-0.012858493" izx="-0.00023992085" izy="-0.012858493" izz="0.11351516" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*tibia_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${tibia_large} ${tibia_width} ${tibia_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*tibia_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${tibia_large} ${tibia_width} ${tibia_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_ankle" >
    <inertial>
      <origin xyz="-0.000214 -0.018536 0.013873" />
      <mass value="0.16710792"/>
      <inertia ixx="0.12079175"  ixy="-0.00079781067"  ixz="-0.00039322246" iyx="-0.00079781067" iyy="0.10885465" iyz="0.0070770117" izx="-0.00039322246" izy="0.0070770117" izz="0.041871103" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*ankle_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ankle_large} ${ankle_width} ${ankle_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*ankle_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ankle_large} ${ankle_width} ${ankle_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_phalange" >
    <inertial>
      <origin xyz="-0.000214 -0.018536 0.013873" />
      <mass value="0.16710792"/>
      <inertia ixx="0.12079175"  ixy="-0.00079781067"  ixz="-0.00039322246" iyx="-0.00079781067" iyy="0.10885465" iyz="0.0070770117" izx="-0.00039322246" izy="0.0070770117" izz="0.041871103" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*phalange_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${phalange_large} ${phalange_width} ${phalange_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${phalange_large} ${phalange_width} ${phalange_height}"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="${side}_pelvis_joint" type="revolute">
    <parent link="${parent}"/>
    <child link="${side}_pelvis"/>
    <origin xyz="0 ${reflect*body_width/2} 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="10" velocity="5.6548668" lower="${-75*M_PI/180}" upper="${45*M_PI/180}" />
  </joint>
  
  <joint name="${side}_thigh_yaw_joint" type="revolute">
    <parent link="${side}_pelvis"/>
    <child link="${side}_thigh_yaw"/>
    <origin xyz="0 ${reflect*pelvis_width/2} ${-1*pelvis_height}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="10" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="${side}_thigh_pitch_joint" type="revolute">
    <parent link="${side}_thigh_yaw"/>
    <child link="${side}_thigh"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="10" velocity="5.6548668" lower="${-75*M_PI/180}" upper="${45*M_PI/180}"  />
  </joint>

  <joint name="${side}_tibia_joint" type="revolute">
    <parent link="${side}_thigh"/>
    <child link="${side}_tibia"/>
    <origin xyz="0 0 ${-1*thigh_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="10" velocity="5.6548668" lower="${0*M_PI/180}" upper="${150*M_PI/180}" />
  </joint>

  <joint name="${side}_ankle_joint" type="revolute">
    <parent link="${side}_tibia"/>
    <child link="${side}_ankle"/>
    <origin xyz="0 0 ${-1*tibia_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="10" velocity="5.6548668" lower="${-90*M_PI/180}" upper="${0*M_PI/180}" />
  </joint>

  <joint name="${side}_phalange_joint" type="revolute">
    <parent link="${side}_ankle"/>
    <child link="${side}_phalange"/>
    <origin xyz="0 0 ${-1*ankle_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="10" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>
</xacro:macro>
</robot>