<?xml version="1.0" ?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="leg">

 <!--xacro:property name="body_height" value="0.106" /-->
 <!--xacro:property name="body_width" value="0.109" /-->
 <!--xacro:property name="body_large" value="0.102" /-->
<xacro:property name="pelvis_height" value="0.028652" />
 <xacro:property name="pelvis_width" value="0.08175" />
 <xacro:property name="pelvis_large" value="0.045" />
 <xacro:property name="thigh_virtual_height" value="0.001" />
 <xacro:property name="thigh_virtual_width" value="0.001" />
 <xacro:property name="thigh_virtual_large" value="0.001" />
<xacro:property name="thigh_height" value="0.125" />
 <xacro:property name="thigh_width" value="0.035" />
 <xacro:property name="thigh_large" value="0.045" />
 <xacro:property name="tibia_height" value="0.130" />
 <xacro:property name="tibia_width" value="0.035" />
 <xacro:property name="tibia_large" value="0.045" />
  <xacro:property name="ankle_height" value="0.0745" />
 <xacro:property name="ankle_width" value="0.035" />
 <xacro:property name="ankle_large" value="0.045" />
   <xacro:property name="phalange_height" value="0.0745" />
 <xacro:property name="phalange_width" value="0.020" />
 <xacro:property name="phalange_large" value="0.020" />
   <!-- Friction model from "Characterization and modeling of a Dynamixel servo" by Arno Mensin (model AX12, better than nothing) -->
  <!-- Damping N.m.s/rad --> 
  <xacro:property name="dxl_damping" value="0.15" />
  <!-- Friccion N.m -->
  <xacro:property name="dxl_friction" value="0.3" />
  <xacro:macro name="cuboid_inertia_def" params="x y z mass">
    <inertia 
      iyy="${mass*(z*z+x*x)/12.0}"
      ixx="${mass*(y*y+z*z)/12.0}"
      izz="${mass*(x*x+y*y)/12.0}"
      ixy="0.0" iyz="0.0" ixz="0.0"/>
  </xacro:macro>
  <xacro:macro name="leg" params="side parent reflect body_height body_width body_large">

      <!-- Transmissions -->
    <xacro:joint_transmission joint="${side}_thigh_pitch_joint"/>
    <xacro:joint_transmission joint="${side}_tibia_joint"/>
    <xacro:joint_transmission joint="${side}_ankle_joint"/>
    <xacro:joint_transmission joint="${side}_phalange_joint"/>
  <link name="${side}_pelvis" >
    <inertial>
      <origin xyz="0 0 ${-1*pelvis_height/2}" />
      <mass value="0.3"/>
      <xacro:cuboid_inertia_def x="${pelvis_large}" y="${pelvis_width}" z="${pelvis_height}" mass="0.3"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*pelvis_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${pelvis_large} ${pelvis_width} ${pelvis_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*pelvis_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${pelvis_large} ${pelvis_width} ${pelvis_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_thigh_yaw" >
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <xacro:cuboid_inertia_def x="${thigh_virtual_large}" y="${thigh_virtual_width}" z="${thigh_virtual_height}" mass="0.6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_virtual_large} ${thigh_virtual_width} ${thigh_virtual_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${thigh_virtual_large} ${thigh_virtual_width} ${thigh_virtual_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_thigh" >
    <inertial>
      <origin xyz="0 0 ${-1*thigh_height/2}" />
      <mass value="0.8"/>
      <xacro:cuboid_inertia_def x="${thigh_large}" y="${thigh_width}" z="${thigh_height}" mass="0.8"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*thigh_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_large} ${thigh_width} ${thigh_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*thigh_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${thigh_large} ${thigh_width} ${thigh_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_tibia" >
    <inertial>
      <origin xyz="0 0 ${-1*tibia_height/2}" />
      <mass value="0.6"/>
      <xacro:cuboid_inertia_def x="${tibia_large}" y="${tibia_width}" z="${tibia_height}" mass="0.6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*tibia_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${tibia_large} ${tibia_width} ${tibia_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*tibia_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${tibia_large} ${tibia_width} ${tibia_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="${side}_ankle" >
    <inertial>
      <origin xyz="0 0 ${-1*ankle_height/2}" />
      <mass value="0.3"/>
      <xacro:cuboid_inertia_def x="${ankle_large}" y="${ankle_width}" z="${ankle_height}" mass="0.3"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*ankle_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ankle_large} ${ankle_width} ${ankle_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*ankle_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ankle_large} ${ankle_width} ${ankle_height}"/>
      </geometry>
        <friction>
          <ode>
            <mu>20000</mu>
            <mu2>20000</mu2>
          </ode>
        </friction>
    </collision>
  </link>

  <link name="${side}_phalange" >
    <inertial>
      <origin xyz="0 0 ${-1*phalange_height/2}" />
      <mass value="0.1"/>
      <xacro:cuboid_inertia_def x="${phalange_large}" y="${phalange_width}" z="${phalange_height}" mass="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*phalange_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${phalange_large} ${phalange_width} ${phalange_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*phalange_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${phalange_large} ${phalange_width} ${phalange_height}"/>
      </geometry>
       <surface>
        <friction>
          <ode>
            <mu>20000</mu>
            <mu2>20000</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
  </link>
  
  <joint name="${side}_pelvis_joint" type="fixed">
    <parent link="${parent}"/>
    <child link="${side}_pelvis"/>
    <origin xyz="${-body_large/6} ${reflect*body_width/2} ${body_height/5}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <!--limit effort="4" velocity="4" lower="0" upper="0.01" /-->
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>
  
  <joint name="${side}_thigh_yaw_joint" type="fixed">
    <parent link="${side}_pelvis"/>
    <child link="${side}_thigh_yaw"/>
    <origin xyz="0 ${reflect*pelvis_width/2} ${-1*pelvis_height}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <!--limit effort="4" velocity="4" lower="0" upper="0.01" /-->
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>

  <joint name="${side}_thigh_pitch_joint" type="revolute">
    <parent link="${side}_thigh_yaw"/>
    <child link="${side}_thigh"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="8" velocity="6" lower="${-75*M_PI/180}" upper="${45*M_PI/180}"  />
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>

  <joint name="${side}_tibia_joint" type="revolute">
    <parent link="${side}_thigh"/>
    <child link="${side}_tibia"/>
    <origin xyz="0 0 ${-1*thigh_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="8" velocity="6" lower="${0*M_PI/180}" upper="${150*M_PI/180}" />
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>

  <joint name="${side}_ankle_joint" type="revolute">
    <parent link="${side}_tibia"/>
    <child link="${side}_ankle"/>
    <origin xyz="0 0 ${-1*tibia_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="8" velocity="6" lower="-2.1" upper="-0.8" />
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>

  <joint name="${side}_phalange_joint" type="revolute">
    <parent link="${side}_ankle"/>
    <child link="${side}_phalange"/>
    <origin xyz="${-1*ankle_large/2} 0 ${-1*ankle_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="8" velocity="6" lower="${-45*M_PI/180}" upper="0" />
    <!--dynamics damping="${dxl_damping}" friction="${dxl_friction}" /-->
  </joint>
</xacro:macro>
</robot>