<?xml version="1.0" ?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="structure"> 
  <xacro:property name="column_height" value="1.25" />
  <xacro:property name="cross_length" value="0.025" />
  <xacro:property name="beam_height" value="20" />
  <xacro:property name="support_height" value="1.30" />  
  <xacro:macro name="structure" params="parent child body_height body_width body_large">
  
  <joint name="fixed" type="fixed">
    <parent link="${parent}"/>
    <child link="column"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>
  <joint name="column_to_beam" type="continuous">
    <parent link="column"/>
    <child link="beam"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${column_height/2}" rpy="0 0 0" />
  </joint>
    <joint name="slider_to_support" type="fixed">
    <parent link="slider"/>
    <child link="support"/>
    <origin xyz="0 0 ${-1*(cross_length/2)}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <!--limit effort="15" velocity="50" lower="${-90*M_PI/180}" upper="${90*M_PI/180}" /-->  
  </joint>
  <joint name="support_to_base_link" type="fixed">
    <parent link="support"/>
    <child link="${child}"/>
    <origin xyz="0 0 ${-support_height}" rpy="0 0 0" />
  </joint>
  <joint name="beam_to_slider" type="fixed">
    <parent link="beam"/>
    <child link="slider"/>
    <origin xyz="0 1 ${-1*cross_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0" />
    <!--limit effort="3" velocity="2" lower="5" upper="20" /-->  
  </joint>
  <link name="column">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="3"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${cross_length}" z="${column_height}" mass="3"/>
    </inertial>
    <visual>
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${column_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${column_height}" />
      </geometry>
    </collision>
  </link>
    <link name="slider">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${cross_length}" z="${cross_length}" mass="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${cross_length}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${cross_length} ${cross_length} ${cross_length}" />
      </geometry>
    </collision>
  </link>
    <link name="support">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.4"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${cross_length}" z="${support_height}" mass="0.4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-1*support_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${support_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-1*support_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${support_height}" />
      </geometry>
    </collision>
  </link>
    <link name="beam">
    <inertial>
      <origin xyz="0 ${beam_height/2} 0" />
      <mass value="8"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${beam_height}" z="${cross_length}" mass="8"/>
    </inertial>
    <visual>
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <origin xyz="0 ${beam_height/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${beam_height} ${cross_length} " />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${beam_height/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${beam_height} ${cross_length} " />
      </geometry>
    </collision>
  </link>

</xacro:macro>
</robot>