<?xml version="1.0" ?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="structure"> 
  <xacro:property name="column_height" value="1.25" />
  <xacro:property name="cross_length" value="0.025" />
  <xacro:property name="beam_height" value="5" />
  <xacro:property name="support_height" value="1.26" />  
  <xacro:macro name="structure" params="parent child body_height body_width body_large">



  
  <joint name="fixed" type="fixed">
    <parent link="${parent}"/>
    <child link="column"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>
  <joint name="column_to_beam" type="continuous">
    <parent link="column"/>
    <child link="beam"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${-column_height/2}" rpy="0 0 0" />
  </joint>

  <joint name="beam_to_base_link" type="fixed">
    <parent link="beam"/>
    <child link="${child}"/>
    <origin xyz="0 ${beam_height} 0" rpy="0 0 0" />
    <!--limit effort="4" velocity="4" lower="0" upper="0.01" /-->
  </joint>

  <link name="column">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="3"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${cross_length}" z="${column_height}" mass="30"/>
    </inertial>
    <visual>
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${column_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${cross_length} ${column_height}" />
      </geometry>
    </collision>
  </link>


    <link name="beam">
    <inertial>
      <origin xyz="0 ${beam_height/2} 0" rpy="0 0 0"/>
      <mass value="8"/>
      <xacro:cuboid_inertia_def x="${cross_length}" y="${beam_height}" z="${cross_length}" mass="80"/>
    </inertial>
    <visual>
      <!--origin xyz="-0.0235 0 -0.03525" rpy="0 0 0" /-->
      <origin xyz="0 ${beam_height/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${beam_height} ${cross_length} " />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${beam_height/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="${cross_length} ${beam_height} ${cross_length} " />
      </geometry>
    </collision>
  </link>

</xacro:macro>
</robot>